### ISSUE TITLE
[VITA] No config file

### ISSUE THREAD

**Issue by Electric1447** [Ch0wW/odamex#61] opened 2019-12-07 19:32 UTC
It doesn't create a config file.
Also it doesn't save any changes made to the configuration.

Tested on PS VITA running enso 3.65

**Comment by Ch0wW** [comment] 2019-12-10 17:07
Can you test this ? I just tried it again, and it definitely saveed an odamex.cfg file.
[odamex.zip](https://github.com/Ch0wW/odamex/files/3946177/odamex.zip)

Also, can you make sure you have a the folder odamex created in ux0:/data/ ?

**Comment by Electric1447** [comment] 2019-12-10 17:09
I have it

**Comment by Ch0wW** [comment] 2019-12-11 22:24
Have you been able to test it, to see if the problem still happens on your side ?

**Comment by Ch0wW** [comment] 2019-12-29 01:30
Since there was no news, and that another user confirmed that it works on their PSTV, I'm closing the ticket.

**Closed by Ch0wW** 2019-12-29 01:30 UTC
Labels: CLIENT, PSVita
